---
- hosts: test
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/naveen/ansible/index.html
        dest: /var/www/html/
    - name: start httpd service
      service:
             name: httpd
             state: started
